parameters:
    database_driver: pdo_mysql
    database_host: 127.0.0.1
    database_port: 3306
    database_name: newwly
    database_user: newwly
    database_password: password
    mailer_transport: smtp
    mailer_host: 127.0.0.1
    mailer_user: null
    mailer_password: null
    locale: de
    secret: fe356ea2210e89d66cb5b5f3c35b1c3a4
    database_path: null
