newwly_dashboard:
    resource: "@NewwlyDashboardBundle/Resources/config/routing.yml"
    prefix:   /dashboard

newwly_user:
    resource: "@NewwlyUserBundle/Resources/config/routing.yml"
    prefix:   /

