Newwly\UserBundle\Entity\User:
    type:  entity
    table: newwly_user
    id:
        id:
            type: integer
            generator:
                strategy: AUTO
    fields:
        kindlemail:
            type: string
            length: 255
            
