Newwly\UserBundle\Entity\User:
  constraints:
    - Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity: {fields: kindlemail, message: fos_user.kindlemail.already_used, groups: [Registration, Profile]}
  properties:
    kindlemail:
          - NotBlank: {message: fos_user.kindlemail.blank, groups: [Registration, Profile]}
          - Length: {min: 3, minMessage: fos_user.kindlemail.short, max: 254, maxMessage: fos_user.kindlemail.long, groups: [Registration, Profile]}
          - Email: {message: fos_user.kindlemail.invalid, groups: [Registration, Profile]}